### ISSUE TITLE
Security bug with threshold

### ISSUE THREAD

**Issue by OleksandrShtepa** [lapets/shamirs#2]
There is a security bug in the library.
`shamirs.shares(value, quantity, threshold)`
actually works as:
`shamirs.shares(value, quantity, threshold-1)`
So shares() outputs unmodified **value** if threshold==2:
```
>>> shares(1234, quantity=3, threshold=2, modulus=10000)
[share(1, 1234, 10000), share(2, 1234, 10000), share(3, 1234, 10000)]
>>> interpolate(shares(1234, quantity=10, threshold=5)[:4])
1234
```

**Comment by lapets** [comment]
Thanks!
